### ISSUE TITLE
[BUG] - NLM Ingestor Error - height is missing

### ISSUE THREAD

**Issue by young-developer** [Open-Source-Legal/OpenContracts#148]
```
error uploading file, stacktrace:  Traceback (most recent call last):
nlm-ingestor     |   File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 61, in parse_document
nlm-ingestor     |     return_dict, _ = ingestor_api.ingest_document(
nlm-ingestor     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor     |   File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 28, in ingest_document
nlm-ingestor     |     ingestor = pdf_ingestor.PDFIngestor(doc_location, parse_options)
nlm-ingestor     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor     |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 40, in __init__
nlm-ingestor     |     tika_html_doc = parse_pdf(doc_location, parse_options)
nlm-ingestor     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor     |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 76, in parse_pdf
nlm-ingestor     |     parse(parsed_content)
nlm-ingestor     |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 114, in parse
nlm-ingestor     |     page_height = float(page_kv['height'].replace("px", ""))
nlm-ingestor     |                         ~~~~~~~^^^^^^^^^^
nlm-ingestor     | KeyError: 'height'
```
Pdf example: [2017-2278.pdf](https://github.com/user-attachments/files/16194900/2017-2278.pdf)

**Comment by JSv4** [comment]
Thx. Will try to take a look tonight Eastern

**Comment by rmast** [comment]
[175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.pdf](https://github.com/user-attachments/files/16197791/175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.pdf)

**Comment by rmast** [comment]
nlm-ingestor       | 172.18.0.6 - - [12/Jul/2024 18:00:30] "POST /api/parseDocument?calculate_opencontracts_data=yes&applyOcr=no HTTP/1.1" 500 -
celeryworker_1     | [2024-07-12 18:00:30,899: INFO/SpawnProcess-1] Task opencontractserver.tasks.doc_tasks.nlm_ingest_pdf[77e69dbd-4398-4df5-bd3d-d1c203cab300] received
celeryworker_1     | [2024-07-12 18:00:30,900: INFO/ForkPoolWorker-1] Task opencontractserver.tasks.doc_tasks.nlm_ingest_pdf[77e69dbd-4398-4df5-bd3d-d1c203cab300] retry: Retry in 0s: HTTPError('500 Server Error: INTERNAL SERVER ERROR for url: http://nlm-ingestor:5001/api/parseDocument?calculate_opencontracts_data=yes&applyOcr=no')
celeryworker_1     | [2024-07-12 18:00:30,905: INFO/ForkPoolWorker-1] nlm_ingest_pdf() - split doc 4 for user 2
nlm-ingestor       | error uploading file, stacktrace: Traceback (most recent call last):
nlm-ingestor       |   File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 61, in parse_document
nlm-ingestor       |     return_dict, _ = ingestor_api.ingest_document(
nlm-ingestor       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 28, in ingest_document
nlm-ingestor       |     ingestor = pdf_ingestor.PDFIngestor(doc_location, parse_options)
nlm-ingestor       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 40, in __init__
nlm-ingestor       |     tika_html_doc = parse_pdf(doc_location, parse_options)
nlm-ingestor       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 76, in parse_pdf
nlm-ingestor       |     parse(parsed_content)
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 114, in parse
nlm-ingestor       |     page_height = float(page_kv['height'].replace("px", ""))
nlm-ingestor       |                         ~~~~~~~^^^^^^^^^^
nlm-ingestor       | KeyError: 'height'
nlm-ingestor       | Traceback (most recent call last):
nlm-ingestor       |   File "/app/nlm_ingestor/ingestion_daemon/__main__.py", line 61, in parse_document
nlm-ingestor       |     return_dict, _ = ingestor_api.ingest_document(
nlm-ingestor       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/ingestor_api.py", line 28, in ingest_document
nlm-ingestor       |     ingestor = pdf_ingestor.PDFIngestor(doc_location, parse_options)
nlm-ingestor       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 40, in __init__
nlm-ingestor       |     tika_html_doc = parse_pdf(doc_location, parse_options)
nlm-ingestor       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 76, in parse_pdf
nlm-ingestor       |     parse(parsed_content)
nlm-ingestor       |   File "/app/nlm_ingestor/ingestor/pdf_ingestor.py", line 114, in parse
nlm-ingestor       |     page_height = float(page_kv['height'].replace("px", ""))
nlm-ingestor       |                         ~~~~~~~^^^^^^^^^^
nlm-ingestor       | KeyError: 'height'
nlm-ingestor       | 172.18.0.6 - - [12/Jul/2024 18:00:30] "POST /api/parseDocument?calculate_opencontracts_data=yes&applyOcr=no HTTP/1.1" 500 -

**Comment by rmast** [comment]
I tried to find back the "parse(parsed_content)" in (https://github.com/nlmatics/nlm-ingestor) but no hit.
Could that point to an old version or a fork of nlm-ingestor?

**Comment by rmast** [comment]
It appears to be this fork:
https://github.com/JSv4/nlm-ingestor/blob/main/nlm_ingestor/ingestor/pdf_ingestor.py

**Comment by rmast** [comment]
That fork has no separate issues-tab, so this issue on the OpenContracts-repo appears to be valid.

**Comment by rmast** [comment]
The commit this faulty code is in is called "Think I got PAWLs output for non-OCRed PDFs.".
So that leads to the assumption this code is meant for allowing non-OCRed PDFs that weren't allowed before, but might be poorly tested yet.

Conclusion would be to first OCR the PDF with for example OCRmyPDF to try a path that has worked before.

**Comment by JSv4** [comment]
Thanks, @rmast. I would like to move off that fork, but I needed to do some post-processing that made more sense in the nlm-ingestor parser. Not 100% sure the best way to contribute it back. Anyway... the issue is related to my fork, but the cause of the bug appears to be nlm-ingestor not retrieving valid pages when running line 166 of `parse_and_apply_hocr`. Do the sample PDFs you're using work in the main nlm-ingestor branch and produce text output?

**Comment by JSv4** [comment]
@rmast, if you have some more time to poke around here (I'm running short, unfortunately), I noticed the output html from the [first pdf example](https://github.com/user-attachments/files/16194900/2017-2278.pdf) is missing style information (see call to get html from Tika [here](https://github.com/JSv4/nlm-ingestor/blob/ecc6968a50fdbd0c6095b70cc78d5a6d9fd7ea2e/nlm_ingestor/ingestor/pdf_ingestor.py#L97C1-L98C1)). The lack of style information - which should contain the page sizes - is causing failures down the parser pipeline.

**Comment by rmast** [comment]
If you like to spin some open source support for this repo I think the main thing should be to lower the bar to see it the intended software working, for example by a live demo, or at least a pointer to a working tag or branch. Or a video of the working?

Niharika Singh used words like 'robust' for this pipeline, but I can't see it.
https://www.marktechpost.com/2024/07/10/open-contracts-the-free-and-open-source-document-analytics-platform/

**Comment by JSv4** [comment]
Thanks for the feedback. Have you tried other documents? There are several hundred installs and for the most part not many open issues. There's something about these two German PDFs that make nlm ingestor unhappy. Happy to try to figure that out with you.

**Comment by rmast** [comment]
I guess this workflow could be helpful debugging the nlm-ingestor:
https://github.com/nlmatics/nlm-ingestor/blob/main/notebooks/pdf_visual_ingestor_step_by_step.ipynb

**Comment by rmast** [comment]
I have a hypothesis about my issue, it seems to recognize the 1 out of 4 pages on the right bottom and states something about caching it, so I made a full unsearchable PDF of 4 pages to try.
[Formulier-14-print-to-2.pdf](https://github.com/user-attachments/files/16286700/Formulier-14-print-to-2.pdf)

**Comment by rmast** [comment]
It's now reading 3 out of 4 pages, and complaints about missing pages, because the text on the last page states some id should be included and also something else not necessary:

(nlm-ingestor) rmast@rmast-virtual-machine:~/nlm-ingestor$ python -m nlm_ingestor.ingestion_daemon
 * Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.178.171:5001
Press CTRL+C to quit
processing page:  0  Number of p_tags....  70
**group buf still has:  1       blad      1      van      4**
127.0.0.1 - - [18/Jul/2024 16:50:20] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes HTTP/1.1" 200 -
processing page:  0  Number of p_tags....  70
**group buf still has:  1       blad      1      van      4**
127.0.0.1 - - [18/Jul/2024 17:10:51] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes&useNewIndentParser=yes HTTP/1.1" 200 -
processing page:  0  Number of p_tags....  76
processing page:  1  Number of p_tags....  102
processing page:  2  Number of p_tags....  59
processing page:  3  Number of p_tags....  60
group buf still has:  1       Eventueel      meesturen:
processing blocks in page:  1
processing blocks in page:  2
processing blocks in page:  3
127.0.0.1 - - [18/Jul/2024 19:09:13] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes&useNewIndentParser=yes HTTP/1.1" 200 -
^C(nlm-ingestor) rmast@rmast-virtual-machine:~/nlm-ingestor$ python -m nlm_ingestor.ingestion_daemon
 * Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.178.171:5001
Press CTRL+C to quit
processing page:  0  Number of p_tags....  76
processing page:  1  Number of p_tags....  102
processing page:  2  Number of p_tags....  59
processing page:  3  Number of p_tags....  60
**group buf still has:  1       Eventueel      meesturen:**
processing blocks in page:  1
processing blocks in page:  2
processing blocks in page:  3
127.0.0.1 - - [18/Jul/2024 19:12:05] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes&useNewIndentParser=yes HTTP/1.1" 200 -

**Comment by rmast** [comment]
Downgrading to nlm-ingestor v0.1.4 reveals bboxes with texts.

**Comment by JSv4** [comment]
Thanks @rmast, that was really helpful. I think the bug we're seeing is related to [issue # 72 in nlm-ingestor](https://github.com/nlmatics/nlm-ingestor/issues/72). Like I said, the issue is with some PDFs (a small number I think), there is no style property in Tika output in nlm-ingestor. I do some additional post-processing to export token-level annotations that nlm-ingestor doesn't do, so our error is popping up a couple lines later:

![image](https://github.com/user-attachments/assets/9d017da7-1a6d-41cb-855d-d3302429cda0)

I hoped that [nlm-ingestor PR # 70](https://github.com/nlmatics/nlm-ingestor/pull/70) would fix the issue, but no dice. I will try to debug this some more this weekend if I have time. 

Are any documents working for you? I've not run into this issue myself. I wonder if it's something about how your PDF converter is building its outputs? Not sure how familiar you are with PDF, but one of the biggest issues with it is there are a LOT of ways to export / import and this creates some complexity.

**Comment by JSv4** [comment]
Do you want to give the latest nlm-ingestor code through PR # 70 a shot? The comments there suggest it works,

**Comment by rmast** [comment]
I'm afraid I'm confusing hardware-issues. Yesterday I started on a 20 GB RAM AMD FX-6300 that still doesn't give good results whatsoever, however when I run a modern Azure server with the main branch of nlm-ingestor it just gives text in those bounding boxes with the same PDF. I downgraded both conda environments to python==3.8.

**Comment by rmast** [comment]
I ruled out most possible hardware causes. My test still fails when the nlm-ingestor runs on Azure and only this locally:
from llmsherpa.readers import LayoutPDFReader
pdf_reader = LayoutPDFReader(llmsherpa_api_url)
doc = pdf_reader.read_pdf(pdf_url)
When I run those lines on Azure they complete.

I read some comments about putting a wsgi server inbetween, but I think the http client in the llmsherpa python-library is probably cranky.

**Comment by rmast** [comment]
I tried the https://github.com/nlmatics/nlm-ingestor/pull/70 both remotely, local and only a local llmsherpa.

Results: Fully Remote, directly followed by local llmsherpa, no difference:
```
python -m nlm_ingestor.ingestion_daemon
/home/rmast/miniconda3/envs/nlm-ingestor/lib/python3.8/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
 * Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.11.0.4:5001
Press CTRL+C to quit
processing page:  0  Number of p_tags....  76
processing page:  1  Number of p_tags....  79
processing page:  2  Number of p_tags....  48
processing page:  3  Number of p_tags....  61
group buf still has:  1       blad      4      van      4
processing blocks in page:  1
processing blocks in page:  2
processing blocks in page:  3
127.0.0.1 - - [19/Jul/2024 19:25:14] "POST /api/parseDocument?renderFormat=all&applyOcr=yes HTTP/1.1" 200 -
processing page:  0  Number of p_tags....  76
processing page:  1  Number of p_tags....  79
processing page:  2  Number of p_tags....  48
processing page:  3  Number of p_tags....  61
group buf still has:  1       blad      4      van      4
processing blocks in page:  1
processing blocks in page:  2
processing blocks in page:  3
217.62.228.60 - - [19/Jul/2024 19:34:39] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes HTTP/1.1" 200 -

```
Both local runs (fully and llmsherpa) end up this way:

``` 
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ python testje8.py
Traceback (most recent call last):
  File "testje8.py", line 10, in <module>
    doc = pdf_reader.read_pdf(pdf_url)
  File "/home/rmast/llmsherpa/llmsherpa/readers/file_reader.py", line 90, in read_pdf
    blocks = response_json['return_dict']['result']['blocks']
KeyError: 'result'
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ vi testje8.py
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ ls -al /home/rmast/Downloads/Formulier-14-print-to-2.pdf
-rw-rw-r-- 1 rmast rmast 1765906 jul 18 19:13 /home/rmast/Downloads/Formulier-14-print-to-2.pdf
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ vi testje8.py
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ python testje8.py
Traceback (most recent call last):
  File "testje8.py", line 10, in <module>
    doc = pdf_reader.read_pdf(pdf_url)
  File "/home/rmast/llmsherpa/llmsherpa/readers/file_reader.py", line 90, in read_pdf
    blocks = response_json['return_dict']['result']['blocks']
KeyError: 'result'
(nlm-ingestor) rmast@rmast-virtual-machine:~/llmsherpa$ 
``` 

The full local run has other values, but I doubt that to be the cause of the crash:

``` 
python -m nlm_ingestor.ingestion_daemon
 * Serving Flask app '__main__'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.178.171:5001
Press CTRL+C to quit
processing page:  0  Number of p_tags....  76
processing page:  1  Number of p_tags....  102
processing page:  2  Number of p_tags....  59
processing page:  3  Number of p_tags....  60
group buf still has:  1       Eventueel      meesturen:
processing blocks in page:  1
processing blocks in page:  2
processing blocks in page:  3
127.0.0.1 - - [19/Jul/2024 21:29:42] "POST /api/parseDocument?renderFormat=all?&applyOcr=yes HTTP/1.1" 200 -
``` 

So there must be something wrong with the step back to the local llmsherpa, which is both the git main source version.

**Comment by rmast** [comment]
For some reason nlm-ingestor/nlm_ingestor/ingestor/pdf_ingestor.py is entered with render_format='all?' in the local situation.

If I just say 
return_dict["result"] = result[1].get("document", {})
in the debugger console
when the cursor has passed that line on line 49 because render_format='all?' instead of 'all' the output is generated locally.
```
import json
import logging
import re
import numpy as np
from collections import defaultdict, namedtuple
from typing import Optional

from bs4 import BeautifulSoup

from nlm_ingestor.file_parser import pdf_file_parser
from timeit import default_timer
from .visual_ingestor import visual_ingestor
from nlm_ingestor.ingestor.visual_ingestor.new_indent_parser import NewIndentParser
from nlm_ingestor.ingestor_utils.utils import NpEncoder, \
    detect_block_center_aligned, detect_block_center_of_page
from nlm_ingestor.ingestor_utils import utils

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
text_only_pattern = re.compile(r"[^a-zA-Z]+")

class PDFIngestor:
    def __init__(self, doc_location, parse_options):
        self.logger = logging.getLogger(self.__class__.__name__)
        self.logger.setLevel(logging.INFO)
        parse_pages = parse_options.get("parse_pages", False) \
            if parse_options else ()
        render_format = parse_options.get("render_format", "all") \
            if parse_options else "all"
        use_new_indent_parser = parse_options.get("use_new_indent_parser", False) \
            if parse_options else False
        
        tika_html_doc = parse_pdf(doc_location, parse_options)
        # print("tika_html_doc", tika_html_doc)
        blocks, _block_texts, _sents, _file_data, result, page_dim, num_pages = parse_blocks(
            tika_html_doc,
            render_format=render_format,
            parse_pages=parse_pages,
            use_new_indent_parser=use_new_indent_parser
        )
        return_dict = {
            "page_dim": page_dim,
            "num_pages": num_pages,
        }
        if render_format == "json":
            return_dict["result"] = result[0].get("document", {})
        elif render_format == "all":
            return_dict["result"] = result[1].get("document", {})
        self.return_dict = return_dict # Line 49
```

**Comment by rmast** [comment]
And that means the REST-JSON communication is extremely error prone to errors in the query string which contained an extra ?

**Comment by rmast** [comment]
This code does not show the error with the original document, not even on the main of the original nlm-ingestor.

```
from llmsherpa.readers import LayoutPDFReader
llmsherpa_api_url = "http://localhost:5001/api/parseDocument?renderFormat=all&applyOcr=yes"
pdf_url = "/home/rmast/Downloads/2017-2278.pdf"
# Create a PDF reader and read the PDF
pdf_reader = LayoutPDFReader(llmsherpa_api_url)
doc = pdf_reader.read_pdf(pdf_url)
print(doc.to_html())

```
And after upgrading to python==3.10 even the JSv4 branch of the nlm-ingestor doesn't show that error with this code.

**Comment by JSv4** [comment]
Thanks for all of your incredible work here @rmast! I will try to duplicate your work and roll a new version. So, just to make sure we're on the same page, you did get the error to go away on my fork and you think it's due to running Python==3.10? The Dockerfile for the ingestor container uses Python 3.11, oddly. If that's true, though, at least we have a fix and can narrow some things down.

**Comment by rmast** [comment]
The main cause was the lack of validation of the input parameters. I had a small conversaties with claude.ai:


When, in a python service oriented architecture, the nlm-ingestor service expects two distinct values for renderMode, which can be json or all, but doesn't publish those requirements to the consuming llmsherpa read_pdf, as a consumer of this read_pdf, what would be the best approach to keep the code in nlm-ingestor responsible for these requirements, but inform the consumer early?



To address this situation in a Python service-oriented architecture, where the nlm-ingestor service has specific requirements for the `renderMode` parameter but doesn't publish these requirements to the consuming `llmsherpa.read_pdf`, you can consider the following approach:

1. Create an enum in the nlm-ingestor service:

```python
from enum import Enum

class RenderMode(Enum):
    JSON = "json"
    ALL = "all"
```

2. Implement a validation function in the nlm-ingestor service:

```python
def validate_render_mode(render_mode: str) -> RenderMode:
    try:
        return RenderMode(render_mode.lower())
    except ValueError:
        raise ValueError(f"Invalid render_mode. Allowed values are: {', '.join([e.value for e in RenderMode])}")
```

3. Use this validation function in the nlm-ingestor service:

```python
def process_pdf(pdf_content, render_mode: str):
    validated_render_mode = validate_render_mode(render_mode)
    # Rest of the processing logic
```

4. Create a client library for the nlm-ingestor service:

```python
class NlmIngestorClient:
    def __init__(self, base_url):
        self.base_url = base_url

    def read_pdf(self, pdf_content, render_mode: str):
        validated_render_mode = validate_render_mode(render_mode)
        # Make API call to nlm-ingestor service
        # ...

    @staticmethod
    def get_valid_render_modes():
        return [e.value for e in RenderMode]
```

5. Update the llmsherpa.read_pdf function to use this client:

```python
from nlm_ingestor_client import NlmIngestorClient

def read_pdf(pdf_content, render_mode: str):
    client = NlmIngestorClient("http://nlm-ingestor-service-url")
    return client.read_pdf(pdf_content, render_mode)
```

This approach keeps the responsibility for defining and validating the `renderMode` values within the nlm-ingestor service while providing early feedback to consumers. The client library acts as an intermediary, ensuring that validation happens before making the API call.

Consumers of `llmsherpa.read_pdf` can now also query for valid render modes:

```python
from llmsherpa import read_pdf
from nlm_ingestor_client import NlmIngestorClient

valid_modes = NlmIngestorClient.get_valid_render_modes()
print(f"Valid render modes: {', '.join(valid_modes)}")

result = read_pdf(pdf_content, render_mode="json")
```

This solution provides several benefits:
1. It keeps the responsibility for defining and validating render modes in the nlm-ingestor service.
2. It provides early validation and feedback to consumers.
3. It allows consumers to query for valid render modes.
4. It maintains a clean separation of concerns between services.

Would you like me to explain or elaborate on any part of this solution?

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JSv4** [comment]
Thanks @rmast. Just to confirm before I get started, you did get the issue to resolve with the proposed changes?

**Comment by rmast** [comment]
No, those are just hints from a chatbot based on only my memory of the situation. Main line is by implementing of validation to get a clear message whenever there's something wrong with the URL someone feeds to llmsherpa the amount of unexplainable errors due to these human errors in the issues list should lower.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JSv4** [comment]
Gotcha. Well, good news is I've gotten your PDF to parse using a new parse pipeline that will probably be faster too. I need to package it up and want a much more thorough set of tests for it. Stay tuned.

**Comment by rmast** [comment]
Yes, the need for regression tests is another thing to think of when adopting a recently Open Sourced project. That way you can build a showcase of working examples and that enables new volunteers to look for differences between proven working testcase and their own issue.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JSv4** [comment]
Hey @rmast, I fixed the nlm-ingestor issue. At the moment, the new ingestor image is not in the main branch. Try running the application with this local.yml:

```yaml
version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      args:
        - GITHUB_ACTIONS
      dockerfile: ./compose/local/django/Dockerfile
    image: opencontractserver_local_django
    depends_on:
      - postgres
      - redis
      - vector-embedder
      - nlm-ingestor
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: postgres
    image: opencontractserver_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: redis

  nlm-ingestor:
    image: jscrudato/nlm-ingestor-opencontracts_qa:1.8.2
    container_name: nlm-ingestor

  vector-embedder:
    image: jscrudato/vector-embedder-microservice
    container_name: vector-embedder
    environment:
      PORT: 8000

  celeryworker:
    <<: *django
    image: opencontractserver_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: opencontractserver_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: opencontractserver_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower

  frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      image: opencontractserver_local_frontend
      container_name: frontend
      depends_on:
        - django
      env_file:
      - ./.envs/.local/.frontend
      ports:
        - "3000:3000"
      profiles:
        - "fullstack"
```

FYI, your particular PDF needs to be OCR'ed. I have some changes in a pending PR to OpenContracts to apply OCR where it is needed. Currently you have to turn it on for all documents or off for all documents. Change `NLM_INGEST_USE_OCR = False` to `NLM_INGEST_USE_OCR = True` in `settings.base.py`.

**Comment by JSv4** [comment]
Merged into main. Give it a shot. FYI the outputs when OCRing your particular pdf are not great. If I have time I'll see if there's anything that can be done there. I suspect that's an upstream fix needed in nlm-ingestor.

**Comment by rmast** [comment]
It's my document with known issues in Tesseract. Print wis-clear right on top is incomplete, and the line on the bottom is also incomplete. Scribeocr contains a fork of Tesseract which seems to solve the latter.

Getting issues on Tesseract solved is quite hard due to the lack of testing capacity.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JSv4** [comment]
Thank you, @rmast, so it does work? Can you confirm?

As for testing, we use nlm-ingestor for parsing 
 It has a test suite, though somewhat limited atm. I'm sure they'd appreciate a contribution if you're open to it. While perhaps some other engines have a more mature test suite, few can do the layout analysis that nlm-ingestor does. Even things like deepdoc (RagFlow) and deepdocdetection. Gotta love open source 😀 right.

**Comment by rmast** [comment]
I created a new conda environment and downloaded all anew, as I did not know how to make clean such a docker compose.

The document is uploaded and takes some time. The screen stays waiting as the processor has stopped activity at 
celeryworker_1     | [2024-07-22 20:11:56,503: INFO/ForkPoolWorker-1] Task opencontractserver.tasks.embeddings_task.calculate_embedding_for_doc_text[4c37a13e-8845-46b8-9c8a-b7ee1c7ab882] succeeded in 1.0981567389999327s: None
celeryworker_1     | [2024-07-22 20:11:56,506: INFO/SpawnProcess-1] Task opencontractserver.tasks.doc_tasks.set_doc_lock_state[90fd3c22-ea1a-45ee-b331-00216a0be0bf] received
celeryworker_1     | [2024-07-22 20:11:56,535: INFO/ForkPoolWorker-1] Task opencontractserver.tasks.doc_tasks.set_doc_lock_state[90fd3c22-ea1a-45ee-b331-00216a0be0bf] succeeded in 0.024704405999727896s: None


After uploading the document I see the document in the Documents and Annotations tab.
In the documents tab it says I can edit, but I have no idea how, text isn't even selectable.
In the annotations tab I can pick an annotation and click the top right to find the spot of the annotation in the document. It says 'missing document for item'.

I still don't know what I should expect for functionality. The drawing of the document goes quite slow, so probably it is decomposed and recomposed somewhere, but I can't get hold of it in this GUI.

**Comment by JSv4** [comment]
Thanks, @rmast, looks like the processing finished for you based on those logs. We're continuing to improve the workflow. I know it could be better (and it will be!). I'd also encourage you to read the documentation which walks you through basic usage. I'm closing this issue because the underlying parsing issue is resolved. If you have time, I'd definitely encourage you to contribute to nlm-ingestor, particularly test pdfs and test suites. It's a great parser and I'm sure would benefit from your contributions. Thanks for your help.
