### ISSUE TITLE
Start on local

### ISSUE THREAD

**Issue by nihalgurjar47** [Open-Source-Legal/OpenContracts#83]
How to start a project on local?

I followed the your quick-start step,but it's not start on local. 

![Screenshot from 2023-03-01 15-29-08](https://user-images.githubusercontent.com/104414738/222106402-92538a52-31ab-497d-aca9-16f0677bca32.png)

**Comment by JSv4** [comment]
Thanks for the bug report @nihalgurjar47! Yes, you're correct here. I left out a step, sorry! 

In order to start the frontend in the compose stack you need to add `--profile fullstack` to the up command:

```commandline
docker-compose -f local.yml --profile fullstack up
```

Also, FYI, it looks like you went to localhost:8000. The GraphQL playground `http://localhost:8000/graphiql` and Django admin `http://localhost:8000/admin` are at port 8000 **but** the application itself is on port 3000, you need to go to `http://localhost:3000` to use the application.

The [quickstart guide](https://jsv4.github.io/OpenContracts/quick-start/) has been updated with this additional info:
